var hierarchy =
[
    [ "AI", "classAI.html", null ],
    [ "LoadingCoffeePage::AnimationBoxProps", "structLoadingCoffeePage_1_1AnimationBoxProps.html", null ],
    [ "LoadingCoffeePage::AnimationFillProps", "structLoadingCoffeePage_1_1AnimationFillProps.html", null ],
    [ "ArcFace", "classArcFace.html", null ],
    [ "ArucoDetector", "classArucoDetector.html", null ],
    [ "ArucoResult", "structArucoResult.html", null ],
    [ "fusion::BBox", "structfusion_1_1BBox.html", null ],
    [ "BestDistanceResult", "structBestDistanceResult.html", null ],
    [ "Box", "structBox.html", null ],
    [ "BrewController", "classBrewController.html", null ],
    [ "BrewHistory", "structBrewHistory.html", null ],
    [ "gladehelper::BuilderCallback< T, K >", "structgladehelper_1_1BuilderCallback.html", null ],
    [ "Camera", "classCamera.html", null ],
    [ "CameraMultiplexer", "classCameraMultiplexer.html", null ],
    [ "Coffee", "structCoffee.html", null ],
    [ "CoffeeButtonData", "structCoffeeButtonData.html", null ],
    [ "CoffeeController", "classCoffeeController.html", null ],
    [ "SwipeHelper::Config", "structSwipeHelper_1_1Config.html", null ],
    [ "CupDetector", "classCupDetector.html", null ],
    [ "CupMeasurement", "structCupMeasurement.html", null ],
    [ "fusion::CupVolumeEstimator", "classfusion_1_1CupVolumeEstimator.html", null ],
    [ "Database", "classDatabase.html", null ],
    [ "Detection", "structDetection.html", null ],
    [ "signalhelper::DragEventCallback< T >", "structsignalhelper_1_1DragEventCallback.html", null ],
    [ "DRPJob", "structDRPJob.html", null ],
    [ "DRPQueue", "classDRPQueue.html", null ],
    [ "signalhelper::EventButtonCallback< T >", "structsignalhelper_1_1EventButtonCallback.html", null ],
    [ "signalhelper::EventCallback< T >", "structsignalhelper_1_1EventCallback.html", null ],
    [ "signalhelper::EventKeyCallback< T >", "structsignalhelper_1_1EventKeyCallback.html", null ],
    [ "FaceAligner", "classFaceAligner.html", null ],
    [ "FaceDetector", "classFaceDetector.html", null ],
    [ "FaceEmbeddingController", "classFaceEmbeddingController.html", null ],
    [ "FrameUpdateData", "structFrameUpdateData.html", null ],
    [ "SwipeHelper::Impl", "structSwipeHelper_1_1Impl.html", null ],
    [ "MidasEstimator", "classMidasEstimator.html", null ],
    [ "Moildev", "classMoildev.html", null ],
    [ "MoilUndistorter", "classMoilUndistorter.html", null ],
    [ "Navigation", "classNavigation.html", null ],
    [ "Notification", "classNotification.html", null ],
    [ "signalhelper::NotifyCallback< T >", "structsignalhelper_1_1NotifyCallback.html", null ],
    [ "PageRegistry", "classPageRegistry.html", null ],
    [ "PageStack", "classPageStack.html", [
      [ "AromaControlPage", "classAromaControlPage.html", null ],
      [ "CameraConfigPage", "classCameraConfigPage.html", null ],
      [ "ChangeLanguagePage", "classChangeLanguagePage.html", null ],
      [ "CoffeePreferenceCustomPage", "classCoffeePreferenceCustomPage.html", null ],
      [ "CoffeePreferenceNamePage", "classCoffeePreferenceNamePage.html", null ],
      [ "CoffeePreferencePage", "classCoffeePreferencePage.html", null ],
      [ "ConfirmationPage", "classConfirmationPage.html", null ],
      [ "CustomCoffeePage", "classCustomCoffeePage.html", null ],
      [ "CustomizePreferencePage", "classCustomizePreferencePage.html", null ],
      [ "DisplayPage", "classDisplayPage.html", null ],
      [ "EmptySystemPage", "classEmptySystemPage.html", null ],
      [ "FaceDetectionPage", "classFaceDetectionPage.html", null ],
      [ "FactorySettingPage", "classFactorySettingPage.html", null ],
      [ "GreetingOldPersonPage", "classGreetingOldPersonPage.html", null ],
      [ "GreetingPage", "classGreetingPage.html", null ],
      [ "GuestMember", "classGuestMember.html", null ],
      [ "HeatingPage", "classHeatingPage.html", null ],
      [ "HistoriesPage", "classHistoriesPage.html", null ],
      [ "InformationPage", "classInformationPage.html", null ],
      [ "LoadingCoffeePage", "classLoadingCoffeePage.html", null ],
      [ "MainMenuPage", "classMainMenuPage.html", null ],
      [ "MainSetting", "classMainSetting.html", null ],
      [ "MaintenanceCounterPage", "classMaintenanceCounterPage.html", null ],
      [ "MenuListsPage", "classMenuListsPage.html", null ],
      [ "NumberOfStartProductPage", "classNumberOfStartProductPage.html", null ],
      [ "NumberOfStartScreenPage", "classNumberOfStartScreenPage.html", null ],
      [ "OperatingInstructionsPage", "classOperatingInstructionsPage.html", null ],
      [ "PlaceCupPage", "classPlaceCupPage.html", null ],
      [ "ProductCounterPage", "classProductCounterPage.html", null ],
      [ "RinseMilkSystemPage", "classRinseMilkSystemPage.html", null ],
      [ "Setting1Page", "classSetting1Page.html", null ],
      [ "Setting2Page", "classSetting2Page.html", null ],
      [ "Setting3Page", "classSetting3Page.html", null ],
      [ "SettingCameraCalibrationPage", "classSettingCameraCalibrationPage.html", null ],
      [ "StandbyPage", "classStandbyPage.html", null ],
      [ "SwitchSettingPage", "classSwitchSettingPage.html", null ],
      [ "ThankYouPage", "classThankYouPage.html", null ],
      [ "UnitsPage", "classUnitsPage.html", null ],
      [ "VolumeCoffeePage", "classVolumeCoffeePage.html", null ],
      [ "WaterHardnessPage", "classWaterHardnessPage.html", null ],
      [ "detection_page", "classdetection__page.html", null ]
    ] ],
    [ "PaginationButtonData", "structPaginationButtonData.html", null ],
    [ "PreferenceController", "classPreferenceController.html", null ],
    [ "PreferredCoffee", "structPreferredCoffee.html", null ],
    [ "RootWindow", "classRootWindow.html", null ],
    [ "signalhelper::ScrollEventCallback< T >", "structsignalhelper_1_1ScrollEventCallback.html", null ],
    [ "SessionController", "classSessionController.html", null ],
    [ "SwipeHelper", "classSwipeHelper.html", null ],
    [ "SystemMonitor", "classSystemMonitor.html", null ],
    [ "SystemStats", "structSystemStats.html", null ],
    [ "ThreadController", "classThreadController.html", null ],
    [ "ThreadCupData", "structThreadCupData.html", null ],
    [ "ThreadCupLockData", "structThreadCupLockData.html", null ],
    [ "ThreadFaceData", "structThreadFaceData.html", null ],
    [ "ThreadFaceLockData", "structThreadFaceLockData.html", null ],
    [ "ToggleData", "structToggleData.html", null ],
    [ "signalhelper::UniversalCallback< T >", "structsignalhelper_1_1UniversalCallback.html", null ],
    [ "User", "structUser.html", null ],
    [ "UserCoffeePreference", "structUserCoffeePreference.html", null ],
    [ "UserController", "classUserController.html", null ],
    [ "VirtualKeyboard", "classVirtualKeyboard.html", null ],
    [ "fusion::VolumeInput", "structfusion_1_1VolumeInput.html", null ],
    [ "fusion::VolumeResult", "structfusion_1_1VolumeResult.html", null ]
];